# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
project_name: screego
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
    goarm:
      - "6"
      - "7"
    flags:
      - '-tags="netgo osusergo"'
    ldflags:
      - "-s"
      - "-w"
      - "-X main.version={{.Version}}"
      - "-X main.commitHash={{.Commit}}"
      - "-X main.mode=prod"
archives:
  - files:
      - LICENSE
      - README.md
      - screego.config.example
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
checksum:
  disable: true
