name: Build

on:
  workflow_dispatch:

jobs:
  screego:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Golang
        uses: actions/setup-go@main
        with:
          go-version: 'stable'

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: 'lts/Hydrogen'

      - name: Build UI
        run: |
          cd ui
          yarn
          yarn build

      - name: Download Go Modules
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@master
        with:
          version: 'latest'

      - name: Build and Test
        run: |
          go build ./...
          go test -race ./...

      - name: Release with Goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
